General:
  LogSavePath: storage/logs
  LogFileName: log
  LogFileExt: .log
  LogMaxSize: 60
  LogMaxAge: 7
Database:
  # ********************************模拟第三方PACS上传申请单数据*****************************
  # 数据库公共模块
  DBMaxIdleConns: 100
  DBMaxOpenConns: 100
  DBMaxLifetime: 60
  # ******PACS集成平台数据库连接信息******
  DBType: mysql
  DBConn: espacs:Wowjoy@2018@tcp(172.16.255.26:30117)/ms_pacs_interface?charset=utf8
Object:
  # 定时任务规则：秒/分/时/日/月/星期（cron）
  # 每天0-23时每隔10秒执行一次任务
  CronSpec: "*/10 * 0-23 * * ?"
  # 医院HospitalID
  HospitalID: 186924cf3d70dff202fdb6e4242b39ab
  # PACS集成平台接口
  InterfaceURL: http://127.0.0.1:9010/api/v1/PACS/Upload/ApplyAndDicomInfo
  # 数据上传时间范围(单位分钟)
  TimeInterval: 5
